### ISSUE TITLE
F16C(-1,0) integer conversion resulted in a change of sign

### ISSUE THREAD

**Issue by Jeroen6** [PetteriAimonen/libfixmath#1]
The F16C macro returns:
warning: #68-D: integer conversion resulted in a change of sign
When using a negative number.

**Comment by Jeroen6** [comment]
Possible fix by inserting (uint32_t) when using i?
```c
#define FIXMATH_COMBINE_I_M(i, m) \
( \
    ( \
        ((uint32_t)i ) \
        << 16 \
    ) \
    | \
    ( \
        FIXMATH_CONVERT_MANTISSA(m) \
        & 0xFFFF \
    ) \
)```
By the way, the preprocessor intermediate F16C() generates is incredible.

**Comment by PetteriAimonen** [comment]
Hmm, what platform is this on?

**Comment by Jeroen6** [comment]
Cortex M3 using Keil 4.7 (armcc V5.03.0.76).

**Comment by PetteriAimonen** [comment]
There isn't currently anyone really maintaining libfixmath. Though it appears (to my great surprise) that it was me who wrote that macro, I'm having trouble following the logic now :)

**Comment by Jeroen6** [comment]
The pull request says it's from Jonas Zeiger.

My fix above seems to work though. A few things about the issue:
- The warning will not hinder compilation unless you set --diag_error=warning
- The warning is inactive by default.
- The code is not broken.

**Comment by PetteriAimonen** [comment]
Ah, good point. I was beginning to question my memory :)

If you want to pull request the fix, I'll merge it. But otherwise I'm not much interested in maintaining libfixmath.

**Comment by Jeroen6** [comment]
Compiling GCC x86 is not my playing field. I can't run the unittests with confidence.
Just leave this issue here so it can be found.
