### ISSUE TITLE
How to run the benchmark

### ISSUE THREAD

**Issue by fananchong** [PetteriAimonen/libfixmath#17]

**Comment by PetteriAimonen** [comment]
Well, in theory, you go in the "benchmarks" folder and type `make run-benchmark-arm` or `make run-benchmark-avr`, but that's unlikely to work with any recent version of qemu. There are some notes here:
https://github.com/PetteriAimonen/libfixmath/blob/master/benchmarks/Makefile

Sadly qemu does not seem to provide interfaces that would be suitable for this kind of testing anymore. In some of my other projects I've moved to executing benchmarks on real hardware or simavr, but I haven't touched libfixmath benchmarks in 8 years so they are quite outdated.
